<?php
defined( 'ABSPATH' ) || exit;

/**
 * Professional robots.txt handler with:
 * - Per-language sitemap declarations
 * - AI crawler directives (GPTBot, Google-Extended, CCBot, etc.)
 * - Clean-param directives for duplicate content prevention
 * - IndexNow key file serving
 */
class PLSEO_Robots {

    private static ?self $instance = null;

    public static function get_instance(): self {
        if ( null === self::$instance ) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {
        add_filter( 'robots_txt', [ $this, 'filter_robots_txt' ], 20, 2 );

        // Serve IndexNow verification key file
        add_action( 'template_redirect', [ $this, 'serve_indexnow_key' ] );
    }

    public function filter_robots_txt( string $output, bool $public ): string {
        if ( ! $public ) {
            return "User-agent: *\nDisallow: /\n";
        }

        $lines = [];

        // Start fresh with a professional robots.txt
        $lines[] = '# robots.txt generated by WT Multi SEO Pro';
        $lines[] = '# Last updated: ' . gmdate( 'Y-m-d H:i:s' ) . ' UTC';
        $lines[] = '';

        // Default user-agent rules
        $lines[] = 'User-agent: *';
        $lines[] = 'Disallow: /wp-admin/';
        $lines[] = 'Allow: /wp-admin/admin-ajax.php';
        $lines[] = 'Disallow: /wp-includes/';
        $lines[] = 'Disallow: /wp-content/uploads/woocommerce_uploads/';
        $lines[] = 'Disallow: /cart/';
        $lines[] = 'Disallow: /checkout/';
        $lines[] = 'Disallow: /my-account/';
        $lines[] = 'Disallow: /*?s=';
        $lines[] = 'Disallow: /*?p=';
        $lines[] = 'Disallow: /tag/*/page/';
        $lines[] = 'Disallow: /category/*/page/';

        // Prevent tracking parameters from creating duplicate content
        $lines[] = '';
        $lines[] = '# Prevent crawling of tracking URLs';
        $lines[] = 'Disallow: /*?utm_*';
        $lines[] = 'Disallow: /*?fbclid=*';
        $lines[] = 'Disallow: /*?gclid=*';
        $lines[] = 'Disallow: /*?ref=*';

        // Crawl-delay (optional)
        $crawl_delay = PLSEO_Helpers::get_option( 'robots_crawl_delay', '' );
        if ( $crawl_delay && is_numeric( $crawl_delay ) ) {
            $lines[] = '';
            $lines[] = 'Crawl-delay: ' . (int) $crawl_delay;
        }

        $lines[] = '';

        // AI Bot directives (GEO optimization)
        if ( PLSEO_Helpers::get_option( 'robots_block_ai_bots', false ) ) {
            $ai_bots = [
                'GPTBot',
                'ChatGPT-User',
                'Google-Extended',
                'CCBot',
                'anthropic-ai',
                'Claude-Web',
                'Bytespider',
                'PerplexityBot',
                'Amazonbot',
                'FacebookBot',
                'Omgilibot',
                'Diffbot',
                'Applebot-Extended',
                'cohere-ai',
            ];

            $lines[] = '# AI Training Crawler Restrictions';
            foreach ( $ai_bots as $bot ) {
                $lines[] = 'User-agent: ' . $bot;
                $lines[] = 'Disallow: /';
                $lines[] = '';
            }
        } elseif ( PLSEO_Helpers::get_option( 'robots_ai_bots_custom', '' ) ) {
            $custom_rules = trim( (string) PLSEO_Helpers::get_option( 'robots_ai_bots_custom', '' ) );
            if ( $custom_rules ) {
                $lines[] = '# Custom AI Bot Rules';
                $lines[] = $custom_rules;
                $lines[] = '';
            }
        }

        // Sitemap declarations
        if ( PLSEO_Helpers::get_option( 'sitemap_enabled', true ) ) {
            $lines[] = '# Sitemaps';
            $lines[] = 'Sitemap: ' . home_url( 'sitemap.xml' );

            // Per-language sitemaps in robots.txt for better discoverability
            if ( PLSEO_Helpers::get_option( 'sitemap_per_language', false ) ) {
                $langs      = array_keys( PLSEO_Helpers::get_languages() );
                $post_types = [];
                if ( PLSEO_Helpers::get_option( 'sitemap_include_posts', true ) ) {
                    $post_types[] = 'post';
                }
                if ( PLSEO_Helpers::get_option( 'sitemap_include_pages', true ) ) {
                    $post_types[] = 'page';
                }
                foreach ( $langs as $lang ) {
                    foreach ( $post_types as $pt ) {
                        $lines[] = 'Sitemap: ' . home_url( "sitemap-{$lang}-{$pt}.xml" );
                    }
                }
            }

            if ( PLSEO_Helpers::get_option( 'sitemap_news', false ) ) {
                $lines[] = 'Sitemap: ' . home_url( 'sitemap-news.xml' );
            }
            if ( PLSEO_Helpers::get_option( 'sitemap_videos', false ) ) {
                $lines[] = 'Sitemap: ' . home_url( 'sitemap-video.xml' );
            }
            $lines[] = '';
        }

        // Custom additions
        $extra = trim( (string) PLSEO_Helpers::get_option( 'robots_txt_additions', '' ) );
        if ( '' !== $extra ) {
            $lines[] = '# Custom Rules';
            $lines[] = $extra;
            $lines[] = '';
        }

        return implode( "\n", $lines ) . "\n";
    }

    /**
     * Serve the IndexNow key as a text file at /{key}.txt
     */
    public function serve_indexnow_key(): void {
        $key = PLSEO_Helpers::get_option( 'indexnow_api_key', '' );
        if ( ! $key ) {
            return;
        }

        $request_uri = isset( $_SERVER['REQUEST_URI'] ) ? trim( wp_unslash( $_SERVER['REQUEST_URI'] ), '/' ) : '';

        if ( $request_uri === $key . '.txt' ) {
            header( 'Content-Type: text/plain; charset=UTF-8' );
            header( 'X-Robots-Tag: noindex' );
            echo esc_html( $key );
            exit;
        }
    }
}
